### ISSUE TITLE
Cannot figure out how to rebase.

### ISSUE THREAD

**Issue by synic** [gregsexton/gitv#121] opened 2017-04-20 02:10 UTC
The docs are not very clear, typing `grs` on a commit opens the interactive rebase edit window.  If I mark a commit for squash, how do I proceed to the commit message edit dialog?  If I type `:wq` in the interactive rebase window, it closes the preview window and nothing happens.  If I type `grc`, it says the preview window can't be found.

Beyond the keybindings, how does rebasing work in gitv?  It is very unclear

**Comment by rbong** [comment] 2017-04-20 13:52
Thank you for your feedback, it's badly needed for the new features.

I was sure there was a rebasing guide in the doc - I seem to be mistaken. I'll get on that.

Here is a short guide to get you started
- The feature is a wrapper around `git rebase --interactive`
- You can edit the rebase `todo` file in the preview window during rebasing
- You can also stage rebase commands directly onto commits from the commit browser using keybindings before starting the rebase operation if you prefer an inline solution
-  The command keybindings are `grR` (reword), `grE` (edit), `grS` (squash), `grF` (fixup), `grX` (execute), or `grD` (drop) by default
- Press `grs` on a commit to rebase onto your current head, or select a range to rebase between the two ends. `grs` will also enable rebase mode if rebasing was started outside of gitv
- `grs` disables rebase mode once it has been started
- If you have not staged commands, you will be started in `edit` mode on the commit before your `from` target (instead of on the current commit as with `git rebase --interactive` because of limitations of the mode)
- Once you are stopped in `edit` mode or `reword` mode or on an error, you will be able to edit the todo file by pressing `<CR>` or any of the keys which open a commit on the `Edit rebase todo` special target at the top of the commit browser
- If you have started the rebase operation without staging commands, the `todo` file will automatically be opened
- Once you are ready, press `grc` to continue until the rebase operation pauses or completes
- Press `gra` to abort rebasing

Please let me know if the workflow is sufficient. I see that you expect the rebase to continue when you write to and close the `todo` file. The problem I have with automatically starting the rebase operation when writing to and closing the `todo` file is that the user could just want to save and look at commits before continuing. I would be more open to a keybinding or command that writes the todo file and immediately starts.

As far as `preview window can't be found` goes, I can't recreate this, but I think that this can happen if the rebase operation fails. I'll work on getting better error reporting for this. However, can you send more details? What happens if you run `git rebase --continue` from the console instead of `grc`? What instructions are you using?

**Comment by synic** [comment] 2017-04-20 14:39
I am still not getting it :(

In this image: http://d.pr/i/wqHs/24zXoaTt I've marked the "add gitv plugin" (26628a4) for squash using `grS`.

I believe I am then supposed to start the rebase by typing `grc`, however, pressing `grc` doesn't appear to do anything.

If I press `grs` on the commit, I get this error: http://d.pr/i/POzb/25KkKNII


The "preview window can't be found" thing can be reproduced by starting an interactive rebase using `grs`, and then typing`:wq` in the `todo` file.  It closes the `todo` window, and if you try to do anything in the git tree window, you will get the error.

**Comment by rbong** [comment] 2017-04-20 15:40
The rebase isn't actually started as you stage commands, so you must use `grs` instead of `grc`. I will add feedback on using certain `gr` commands without a rebase actually in progress.

You can't squash the first commit in a rebase because there's nothing to squash into. It sounds like this is what's happening. So the rebase actually ends right away. However, there shouldn't be an error, just feedback. I will fix that.

I am still unable to create the `preview window can't be found` error. Do you have any custom gitv settings? Is there a merge in the rebase range?

**Comment by synic** [comment] 2017-04-20 16:09
The same thing happens if I do it like this instead:

http://d.pr/i/O8SV/4uyb9ti9

If I then put my cursor on that line (commit `2c0308`) and type `grs`, I get the same error.  If I put it on the line below that, I get a commit dialog, but I do not see my previous commit messages (I'm used to seeing something like this:  http://d.pr/i/bQ9Y/40Um45aj

Also, I think you are supposed to be able to squash the last commit, into the one previous.  If I run `git rebase -i 4617ee9`, I see a dialog like this:

http://d.pr/i/WjIy/3rji1iKN  - I can then squash the last commit, which is at the bottom, and saving it brings up this todo dialog, where I can edit the commit messages for all commits involved in the squash: http://d.pr/i/lxNX/3tbILzTX

**Comment by rbong** [comment] 2017-04-20 18:38
The cursor should be on `4617ee9` when you press `grs` for squash to work. However, I just tried your setup and I still can't recreate the error when I run `grs` on a similar setup to `2c0308` on version 7.4 or 8.0. Can you post a minimal `.vimrc` and the output of `vim --version`? Would you also be able to push up a repo I could test on?

Also, when I get to the squash commit, I do see just a regular commit message. However, my version of vim detects that there was a change in the file, and when I reload I get the regular squash message. In other words, there is a race condition, and if you press `:e` you'll get the squash message you're expecting. I do not recall having to do this before, it's possible it's a race condition. I'll try to fix this.

Thank you for all this great feedback!

**Comment by rbong** [comment] 2017-04-21 12:38
Never mind about the repo, I was able to find the repository you were using and could stil not recreate it.

**Comment by rbong** [comment] 2017-04-22 23:01
Installed your vim dotfile repo, could not recreate. Still have to try it on OS X, but in case that doesn't work, can you post the output of `vim --version`? Thanks.

**Comment by synic** [comment] 2017-04-24 14:41
Sorry, went on a mini vacation for the weekend.

```

**Comment by echuraev** [comment] 2017-05-19 06:27
I also have some problems with rebase. I marked commit using `grS` next, I do visual selection and press on `grs` to start rebase. You can see my problem on the gif.
![anim](https://cloud.githubusercontent.com/assets/5525113/26235669/3b4f9c34-3c75-11e7-9eb5-9c8e959893d6.gif)

**Comment by rbong** [comment] 2017-12-12 15:12
There were some rebase bugs fixed recently. I recommend trying again if you're still able.

**Comment by rbong** [comment] 2018-06-09 19:48
I am going to hold off on calling this next version stable until I can do more testing on OSX, I don't want to risk major platform incompatability.

**Comment by rbong** [comment] 2018-06-10 02:16
I am now able to reproduce the behaviour on Linux using the `dotvim` repo, even on the latest version of Gitv.

**Comment by rbong** [comment] 2018-06-10 03:05
Settings like this are causing `No preview window found`:

>set splitright
>set splitbelow

There's also some odd behaviour when starting rebase, which is opening a commit window when rebase begins. Still exploring this.

**Comment by rbong** [comment] 2018-06-10 03:17
Looks like if you squash commits and start on the commit before it, it also causes some issues.

**Comment by rbong** [comment] 2018-06-22 21:10
/

**Closed by rbong** 2018-06-22 21:10 UTC
Labels: bug, in progress
